E_commerce/E_commerce/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static
from django.conf.urls import url 

from . import views
urlpatterns = [
  
    path('', include('core.urls')),
    #url(r'^account/', include('account.urls')),
    url(r'^accounts/', include('allauth.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

E_commerce/core/urls.py
from django.urls import path, include
from django.conf.urls import url 
from .views import ( OrderSammaryView, ItemDetailView)

from . import views

app_name = 'core'
urlpatterns = [
  
    path('', views.item_list, name='item_list'),
    path('connexion', views.connexion, name='connexion'),
    #url(r'Articles/(?P<id>[0-9]+)$',views.details, name='produits'),
    #path('search/', views.search, name='search'),
    #path('', HomeView.as_view(), name='home'),
    path('produits/<slug>/', ItemDetailView.as_view(), name='produits'),
    path('commande', OrderSammaryView.as_view(), name='commande'),
    path('add-to-cart/<slug>/', views.add_to_cart, name="add-to-cart"),
    path('remove-from-cart/<slug>/', views.remove_from_cart, name="remove-from-cart"),
    path('add-to-cart-home-page/<slug>/', views.add_to_cart_home_page, name="add-to-cart-home-page"),
    path('remove-single-from-cart/<slug>/', views.remove_single_from_cart, name="remove-single-from-cart"),
    
   
]

E_commerce/templates/base.html
{% load static%}
<!DOCTYPE html>
<html lang="fr">

  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title> Tradifashion.ci</title>
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">    <link href="{%static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{%static 'css/mdb.min.css' %}" rel="stylesheet">
    <link href="{%static 'css/mdb.lite.min.' %}" rel="stylesheet">
    <link href="{%static 'css/mdb.lite.css' %}" rel="stylesheet">
    <link href="{%static 'css/style.css' %}" rel="stylesheet">
    <link href="{%static 'css/addons-pro/cards-extended.css' %}" rel="stylesheet">
  </head>

  
  <body>
      {% block content%}

      
      {% endblock %}
  </body>
</html>

E_commerce/templates/commande.html
{% extends "base.html" %}


{% block content %}

<br><br><br><br>
<body >
 
    {% load static %}
    {% include "layouts/nav.html" %}

    <div class="container">

      <section class="section my-5 pb-5">

        <div class="table-responsive">

          <table class="table product-table">

            <thead>
              <tr>
                <th class="font-weight-bold">
                    <strong>Nbre</strong>
                </th>
                <th class="font-weight-bold">
                  <strong></strong>
              </th>
                <th class="font-weight-bold">
                  <strong>Article</strong>
                </th>
                <th class="font-weight-bold">
                  <strong>Prix</strong>
                </th>
                <th class="font-weight-bold">
                  <strong>quantité</strong>
                </th>
                <th class="font-weight-bold">
                  <strong>Total</strong>
                </th>
                <th></th>
              </tr>
            </thead>
           
            <tbody>

              {% for order_item in object.items.all %}
              <td>
                <p class="font-weight-bold">{{forloop.counter}}</p>
              </td>
              <td>
                <p ><img src="{{order_item.item.image.url}}" class="card-img-top" alt="sample " 
                  style="max-width: 80px;max-height: 60px;"></p>
              </td> 
                <td>
                  <p >{{order_item.item.title}}</p>
                </td>               
                <td>{{order_item.item.price}}</td>
                <td >
                  <p> 
                      <a href="{%url 'core:remove-single-from-cart' order_item.item.slug %}"><i class="fas fa-minus mr-2"></i></a></i>
                     {{order_item.quantity}} 
                     <a href="{%url 'core:add-to-cart' order_item.item.slug %}"><i class="fas fa-plus ml-2"></i></a></p>
                </td>
                
                <td>
                   <p>
                       {% if order_item.item.discount_price%}
                            {{order_item.get_total_item_price}} fcfa
                            
                       {% else %}
                            {{order_item.get_total_item_discount_price}}fcfa
                       {% endif %}

                       <a style="color:red;" href="{%url 'core:remove-from-cart' order_item.item.slug %}">
                         <i class="fas fa-trash   float-right "></i>
                       </a>

                   </p>
                </td>
              </tr>
              {% empty %}
              <tr>
                  <td colspan="5">
                      Votre panier est vide 
                  </td>
              </tr>
              <td colspan="5">
                <a class="btn btn-primary float-right " href="/">continuer mon shopping</a>
            </td>
              {% endfor %}
              {% if object.get_total%}
              <tr>
                  <td colspan="5" class="font-weight-bold">Total commande</td>
                  <td colspan="5">{{object.get_total}} FCFA</td>
              </tr>
              <tr>
                  <td colspan="5">
                      <a class="btn btn-warning float-right ml-2" href="#">Valider mon achat</a>
                      <a class="btn btn-primary float-right " href="/">continuer mon shopping</a>
                  </td>
              </tr>           
              {% endif %}
            </tbody>

          </table>

        </div>

      </section>

    </div>
{% endblock content %}


    

E_commerce/templates/item_list.html
{% block content%}

<h2>Page des articles</h2>

{% for item in items %}
   {{item}}
{% endfor%}

{% endblock content %}