E_commerce/E_commerce/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static
from django.conf.urls import url 

from . import views
urlpatterns = [
  
    path('', include('core.urls')),
    #url(r'^account/', include('account.urls')),
    url(r'^accounts/', include('allauth.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

E_commerce/core/urls.py
from django.urls import path, include
from django.conf.urls import url 
from .views import ( OrderSammaryView, ItemDetailView)

from . import views

app_name = 'core'
urlpatterns = [
  
    path('', views.item_list, name='item_list'),
    path('connexion', views.connexion, name='connexion'),
    #url(r'Articles/(?P<id>[0-9]+)$',views.details, name='produits'),
    #path('search/', views.search, name='search'),
    #path('', HomeView.as_view(), name='home'),
    path('produits/<slug>/', ItemDetailView.as_view(), name='produits'),
    path('commande', OrderSammaryView.as_view(), name='commande'),
    path('add-to-cart/<slug>/', views.add_to_cart, name="add-to-cart"),
    path('remove-from-cart/<slug>/', views.remove_from_cart, name="remove-from-cart"),
    path('add-to-cart-home-page/<slug>/', views.add_to_cart_home_page, name="add-to-cart-home-page"),
    path('remove-single-from-cart/<slug>/', views.remove_single_from_cart, name="remove-single-from-cart"),
    
   
]

E_commerce/templates/layouts/footer.html
{% load static %}
<footer class="page-footer font-small special-color-dark pt-4">

    <div>
       <a href="#carousel-example-1z" class="fass">
         <i class="fas  fa-arrow-alt-circle-up"></i>
       </a>
     </div>
 
   <div class="container">
 
    
 
     <div class="row">
 
       <div class="col-md-6 mb-4">
 
         <form class="form-inline">
           <br><br><br><br><br><br><br>
           <a href="#">
             <img src="{%static 'img/logo1.jpg' %}">
           </a>
         </form>
 
       </div>
      
       <div class="col-md-6 mb-4">
         <div>Nouveau sur Notre page ?</div> <br>
         <p>Incrivez-vous a nos communications pour recevoir des meilleur offres !!!</p>
         <form class="input-group">
           <input type="text" class="form-control form-control-sm" placeholder="Your email"
             aria-label="Your email" aria-describedby="basic-addon2">
           <div class="input-group-append">
             <button class="btn btn-sm btn-outline-white my-0" type="button" class="btn2">Homme</button>
           </div>
            <div class="input-group-append">
             <button class="btn btn-sm btn-outline-white my-0" type="button">Femme</button>
           </div>
         </form>
 
       </div>
      
 
     </div>
   </div>
  
   <div class="container">
 
     <div class="row text-center d-flex justify-content-center pt-5 mb-3">
 
       <div class="col-md-2 mb-3">
         <h6 class="text">
           <a href="#!">A propos</a>
         </h6>
       </div>
     
       <div class="col-md-2 mb-3">
         <h6 class="text">
           <a href="#!">Nos  produits</a>
         </h6>
       </div>
      
       <div class="col-md-2 mb-3">
         <h6 class="text">
           <a href="#!">Vente sur <b>T</b>fashion</a>
         </h6>
       </div>
      
       <div class="col-md-2 mb-3">
         <h6 class="text">
           <a href="#!">Mode de paiement</a>
         </h6>
       </div>
      
       <div class="col-md-2 mb-3">
         <h6 class="text">
           <a href="#!">Contact</a>
         </h6>
       </div>
       <!-- Grid column -->
 
     </div>
     <!-- Grid row-->
     <hr class="rgba-white-light" style="margin: 0 15%;">
 
     <!-- Grid row-->
     <div class="row d-flex text-center justify-content-center mb-md-0 mb-4">
 
       <!-- Grid column -->
       <div class="col-md-8 col-12 mt-5">
         <p style="line-height: 1.7rem">Nouveau sur le marché, la plateforme Tradifashion est une plateforme de valorisation
         des coutumes de la côte d'ivoire ainsi que plusieurs autres pays affricains.
         Sur notre plateforme nous disposons de plusieurs produits. Pour la livraison 
         nous-nous engageons de livre nos différents produits gratuitement sur le sol 
         ivoirien..</p>
       </div>  
 
     </div>
     <hr class="clearfix d-md-none rgba-white-light" style="margin: 10% 15% 5%;">
 
     <div class="row pb-3">
 
       <div class="col-md-12">
 
         <div class="mb-5 flex-center">
 
           <a class="fb-ic">
             <a href="https://web.facebook.com/home.php">
               <i class="fab fa-facebook-f fa-lg white-text mr-4"> </i>
             </a>
             
           </a>
           <a class="tw-ic">
             <i class="fab fa-twitter fa-lg white-text mr-4"> </i>
           </a>
           <!-- Google +-->
           <a class="gplus-ic">
             <i class="fab fa-google-plus-g fa-lg white-text mr-4"> </i>
           </a>
           <!--Linkedin -->
           <a class="li-ic">
             <i class="fab fa-linkedin-in fa-lg white-text mr-4"> </i>
           </a>
           <!--Instagram-->
           <a class="ins-ic">
             <i class="fab fa-instagram fa-lg white-text mr-4"> </i>
           </a>
           <!--Pinterest-->
           <a class="pin-ic">
             <i class="fab fa-pinterest fa-lg white-text"> </i>
           </a>
 
         </div>
 
       </div>
       <!-- Grid column -->
 
     </div>
     <!-- Grid row-->
 
   </div>
   
   <div class="footer-copyright text-center py-3">© 2020 Copyright:
     <a href="https://mdbootstrap.com/"> Tradifashion.ci</a>
   </div>
   <!-- Copyright -->
 
 </footer>
 <!-- Footer -->

E_commerce/templates/layouts/nav.html
{% extends "base.html" %}

    {% load static %}
    {% load cart_template_tags %}

    {% block content%}
      <nav class="navbar fixed-top navbar-expand-lg navbar-light scrolling-navbar white" id="about1" style="background: #dcdcdc;">

        <a class="navbar-brand" href="{% url 'core:item_list' %}">
          <img src="{% static 'img/logo1.jpg' %}" style="margin: 0px 50px 0px 50px;">
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent-4"
          aria-controls="navbarSupportedContent-4" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent-4">
          <ul class="navbar-nav ml-auto">
            <li>
                <form class="form-inline mr-auto" method="GET" action="#" style="margin: 8px 600px 5px 0px">
                    {% csrf_token %}
                  <div class="form-group">
                    <input type="text" class="form-control" name="srh" id="srh"  placeholder="search" style="width: 350px; height: 50px;">

                     <button type="submit" class="btn btn-default" >rechercher</button>
                  </div>
                 
                </form>                     
            </li>
            
           
            {% comment%}<li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" id="navbarDropdownMenuLink-4" data-toggle="dropdown"
                aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-user"></i> se connecter  </a>
              <div class="dropdown-menu dropdown-menu-right dropdown-primary" aria-labelledby="navbarDropdownMenuLink-4">
                <a class="dropdown-item" href="templates/login.html">se connecter</a>
                <a class="dropdown-item" href="templates/cont.html">s'inscrire</a>
              </div>
            </li> {% endcomment %}
            {% if request.user.is_authenticated%}
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" id="navbarDropdownMenuLink-4" data-toggle="dropdown"
                aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-user"></i> Mon compte  </a>
                
              <div class="dropdown-menu dropdown-menu-right dropdown-primary" aria-labelledby="navbarDropdownMenuLink-4">
                <a class="dropdown-item" href="#"> <i class="fa fa-user"></i>  Mon compte </a>
                <a class="dropdown-item" href=" {% url 'core:connexion' %}"> <i class="fas fa-sign-in-alt"></i>  se connecter </a>
                <a class="dropdown-item" href="#"> <i class="fas fa-user-check"></i></i> s'inscrire </a>
                <a class="dropdown-item" href="#"> <i class="fa fa-heart"></i> Favoris </a>
                <a class="dropdown-item" href="#"> <i class="fa fa-user-plus"></i> deconnecter </a>
                
              </div>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'core:commande' %}">
                <span class="badge badge-danger ml-2">{{request.user|cart_item_count}}</span>
                <i class="fas fa-shopping-cart"></i> Panier                  
              </a>
            </li>
            
            {% else%}
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" id="navbarDropdownMenuLink-4" data-toggle="dropdown"
                aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-user"></i> se connecter  </a>
              <div class="dropdown-menu dropdown-menu-right dropdown-primary" aria-labelledby="navbarDropdownMenuLink-4">
                <a class="dropdown-item" href="{% url 'account_login'%}">se connecter</a>
                <a class="dropdown-item" href="{% url 'account_signup'%}">s'inscrire</a>
              </div>
            </li> 
            
            {% endif %}
          </ul>
        </div>
      </nav>
      {% endblock %}

E_commerce/templates/layouts/script.html
{% extends "base.html" %}


{% block content%}
    {% load static %}
    <script type="text/javascript" src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
    <!-- Bootstrap tooltips -->
    <script type="text/javascript" src="{% static 'js/popper.min.js' %}"></script>
    <!-- Bootstrap core JavaScript -->
    <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
    <!-- MDB core JavaScript -->
    <script type="text/javascript" src="{% static 'js/mdb.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/script.js' %}"></script>

{% endblock content %}